### ISSUE TITLE
44.09

### ISSUE THREAD

**Issue by ablizno** [mifki/df-multiscroll#2]
I would like to compile this for DFHack: 0.44.09-r1 any advice on how to do so would be helpful.

**Comment by lethosor** [comment]
https://github.com/mifki/df-twbt/releases

**Comment by ablizno** [comment]
I have the latest version of TWBT

**Comment by lethosor** [comment]
v6.41 from that link supports DFHack 0.44.09-r1. Does that not work?

**Comment by ablizno** [comment]
Issue refers to the multiscroll plugin, not TWBT.

**Comment by lethosor** [comment]
Shoot, sorry about that. I'll see if I can compile it.

**Comment by lethosor** [comment]
If you want to compile it yourself, you'll have to set DFHACKVER, DF, and DH in the [Makefile](https://github.com/mifki/df-multiscroll/blob/master/Makefile) appropriately. DF is the path to DF, and DH is the path to a DFHack clone with at least `dfhack` built.

**Comment by ablizno** [comment]
Oh duh, a clone. Thank you.

**Comment by lethosor** [comment]
Looks like my copy of clang doesn't have type_traits. Not sure what to do about that.

**Comment by ablizno** [comment]
I keep getting 
`*** No rule to make target `multiscroll.mm', needed by `dist/0.44.09-r1/multiscroll.plug.dylib'.  Stop.`

**Comment by ablizno** [comment]
I get the following error:

 fatal error:
      'CoreProtocol.pb.h' file not found
#include "CoreProtocol.pb.h"

**Comment by lethosor** [comment]
You need to compile DFHack too, at least the `dfhack` target.

**Comment by ablizno** [comment]
No luck compiling DFHack

The C compiler

    "/usr/local/bin/gcc-7"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /Users/admin/Downloads/dfhack-master/CMakeFiles/CMakeTmp

**Comment by lethosor** [comment]
Any more output? Maybe in CMakeFiles/CMakeOutput.log or CMakeError.log?

**Comment by ablizno** [comment]
[CMakeOutput.log](https://github.com/mifki/df-multiscroll/files/1930527/CMakeOutput.log)
[CMakeError.log](https://github.com/mifki/df-multiscroll/files/1930528/CMakeError.log)

**Comment by lethosor** [comment]
It looks like you don't have write access to the build folder or something. Also, you need to actually clone DFHack - follow the instructions [here](http://dfhack.readthedocs.io/en/stable/docs/Compile.html). I think you clicked "download ZIP", which just gives you DFHack, not submodules.

**Comment by ablizno** [comment]
[CMakeOutput.log](https://github.com/mifki/df-multiscroll/files/1930556/CMakeOutput.log)

**Comment by ablizno** [comment]
[CMakeOutput.log](https://github.com/mifki/df-multiscroll/files/1930569/CMakeOutput.log)
Getting something about SDL now.

**Comment by lethosor** [comment]
I don't see anything about SDL in that log. Is something wrong in that log? I don't think everything printed to the terminal ends up there.

Also, you should probably try building multiscroll now, pointing it to your DFHack folder, to see if you run into the same issue with type_traits that I did.

**Comment by ablizno** [comment]
Will do once i get dfhack working

Edit: 
Undefined symbols for architecture x86_64:
  "_SDL_Init", referenced from:
      _DFH_SDL_Init in Hooks-darwin.cpp.o
      _interpose_SDL_Init       in Hooks-darwin.cpp.o
     (maybe you meant: _DFH_SDL_Init)
  "_SDL_NumJoysticks", referenced from:
      _interpose_SDL_NumJoysticks       in Hooks-darwin.cpp.o
     (maybe you meant: _DFH_SDL_NumJoysticks)
  "_SDL_PollEvent", referenced from:
      _DFH_SDL_PollEvent in Hooks-darwin.cpp.o
      _interpose_SDL_PollEvent       in Hooks-darwin.cpp.o
     (maybe you meant: _DFH_SDL_PollEvent)
  "_SDL_Quit", referenced from:
      _DFH_SDL_Quit in Hooks-darwin.cpp.o
      _interpose_SDL_Quit       in Hooks-darwin.cpp.o
     (maybe you meant: _DFH_SDL_Quit)
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[2]: *** [library/libdfhack.1.0.0.dylib] Error 1
make[1]: *** [library/CMakeFiles/dfhack.dir/all] Error 2
make: *** [all] Error 2

Once I get this worked out ill try it.

**Comment by ablizno** [comment]
No luck compiling the plugin, i tried doing it with dfhack not compiled an no luck. Different unmet dependancy errors, but not the one you are getting.

**Comment by lethosor** [comment]
What errors specifically?
For the SDL stuff, you need to give cmake the path to the DF folder. Again, see http://dfhack.readthedocs.io/en/stable/docs/Compile.html.

**Comment by ablizno** [comment]
I did that, I get all the way to

`[ 49%] Linking CXX shared library libdfhack.dylib`

**Comment by lethosor** [comment]
Did you pass `-DCMAKE_INSTALL_PREFIX=/path/to/DF` to cmake (and is the path right)?

**Comment by ablizno** [comment]
i have tried static and relative pathing

`cmake .. -DCMAKE_BUILD_TYPE:string=Release -DCMAKE_INSTALL_PREFIX=/Users/ablizno/Downloads/df_osx`

`cmake .. -DCMAKE_BUILD_TYPE:string=Release -DCMAKE_INSTALL_PREFIX=../../df_osx`

both cancel at the same place. I even made sure that the df version I have is the same version and that it runs.

**Comment by lethosor** [comment]
What about specifying the architecture? You'll need to specify `-DDFHACK_BUILD_ARCH=64` if you didn't, since TWBT is 64-bit-only.

**Comment by ablizno** [comment]
Still getting the same errors when i try to `make install`

When running the cmake again i get this warning

`-- Configuring done
WARNING: Target "dfhack" requests linking to directory "/Users/ablizno/downloads/dfhack/build-osx/SDL".  Targets may link only to libraries.  CMake is dropping the item.
-- Generating done
-- Build files have been written to: /Users/ablizno/downloads/dfhack/build-osx`

**Comment by lethosor** [comment]
build-osx/SDL should be a file (it gets copied from your DF folder). Is it not?

**Comment by ablizno** [comment]
OMG thank you, SDL (file) was in a folder called (SDL) I coppied it out of the folder. Got DFHack compiled and the Multiscroll plugin. Here is my output from compiling the plugin if it helps you

`clang -std=gnu++0x -stdlib=libstdc++ -ObjC++ multiscroll.mm -o dist/0.44.09-r1/multiscroll.plug.dylib -DDFHACK_VERSION=\"0.44.09-r1\" -DDF_`echo 0.44.09-r1 | sed -e s/-.*// -e s/\\\\.//g` -I"/Users/ablizno/Downloads/dfhack/library/include" -I"/Users/ablizno/Downloads/dfhack/library/proto" -I"/Users/ablizno/Downloads/dfhack/depends/protobuf" -I"/Users/ablizno/Downloads/dfhack/depends/lua/include" -m64 -DLINUX_BUILD -O3 -D_GLIBCXX_USE_CXX11_ABI=0 -Wno-tautological-compare -L"/Users/ablizno/Downloads/dfhack/build-osx/library" -ldfhack -ldfhack-version -shared  -framework AppKit -mmacosx-version-min=10.6 -undefined dynamic_lookup
ld: warning: object file (/Users/ablizno/Downloads/dfhack/build-osx/library/libdfhack-version.a(DFHackVersion.cpp.o)) was built for newer OSX version (10.9) than being linked (10.6)
`

**Comment by ablizno** [comment]
Attached is the newly compiled multiscroll for the latest df and dfhack if it helps in any way.
[multiscroll.plug.dylib.zip](https://github.com/mifki/df-multiscroll/files/1934081/multiscroll.plug.dylib.zip)

**Comment by lethosor** [comment]
I'm guessing you have a newer version of clang than I do (I have 7.3.0). I still haven't had any luck getting it to work on my end, but since you can build it, mifki probably can too.

**Comment by ablizno** [comment]
Apple LLVM version 9.1.0 (clang-902.0.39.1)
 
Im on the devlopers beta so maybe that makes a difference?
